# Generated by Django 4.0.4 on 2022-05-27 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('company', models.CharField(max_length=120)),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('user_level', models.CharField(choices=[('L0', 'normal user'), ('L1', 'Level one'), ('L2', 'Level two'), ('L3', 'Level three')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporting_person', models.CharField(max_length=100)),
                ('status_code', models.CharField(choices=[('404', '404'), ('304', '404'), ('500', '500'), ('501', '500'), ('502', '502'), ('other', 'Other')], default='other', max_length=30)),
                ('module', models.CharField(choices=[('attendence', 'Attendence'), ('payroll', 'PayRoll'), ('leave', 'Leave'), ('calender', 'Calender'), ('worklog', 'Worklog'), ('other', 'Other')], default='other', max_length=30)),
                ('priority', models.CharField(choices=[('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW')], max_length=30)),
                ('company_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('solved', 'Solved'), ('forward', 'forward')], default='pending', max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermodel', to='IssueTracker.user_types')),
            ],
            options={
                'permissions': (('view_Issue', 'can see issue'), ('report_issue', 'user can report issue'), ('forward_issue', 'user can forwad isuue to senior level'), ('solve_Issue', 'can solve Issue')),
            },
        ),
    ]
