# Generated by Django 4.0.4 on 2022-06-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IssueTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('solved', 'Solved'), ('forward', 'Forward')], default='pending', max_length=20),
        ),
    ]
