# Generated by Django 4.0.4 on 2022-06-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IssueTracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='recipent',
        ),
    ]
